In [1]:
# https://nbviewer.jupyter.org/github/abarto/embedding_interactive_charts_on_an_ipython_notebook/blob/master/
     # embedding_interactive_charts_on_an_ipython_notebook.ipynb#sub_est_2012_df_by_state_template

In [2]:
# Some stuff about D3 and Notebooks. by Jupyter

In [4]:
import pandas as pd
import jinja2

from collections import OrderedDict
from json import dumps
from IPython.html.widgets import interact
from IPython.html import widgets
from IPython.display import display, display_pretty, Javascript, HTML
from IPython.utils.traitlets import Any, Bool, Dict, List, Unicode
from threading import Lock
from urllib.request import urlopen

# Embedding Interactive Charts on an IPython Notebook

## Introduction

In this three part post we’ll show you how easy it is to integrate D3.js, Chart.js and HighCharts chart into an notebook and how to make them interactive using HTML widgets.

## Requirements

The only requirement to run the examples is IPython Notebook version 2.0 or greater. All the modules that we reference are either in the standard Python distribution, or are dependencies of IPython.

## About the Data

All the data that we use in the examples are taken from the United States Census Bureau site (census.gov). We're going to use 2012 population estimates and we're going to plot the sex and age groups by the state, region and division.

## Population by State

We're going to build a Pandas DataFrame from the dataset of <a href="http://www.census.gov/popest/data/cities/totals/2012/SUB-EST2012.html"> Incorporated Places and Minor Civil Divisions</a>. We could have just grabbed the <a href="http://www.census.gov/popest/data/state/totals/2012/index.html"> estimates for the states</a>, but also wanted to show you how easy it is to work with data using Pandas. First, we fetch the data using urlopen and we parse the response as CSV using Pandas' read_csv function:

In [13]:
# https://www.census.gov/data/tables/time-series/demo/popest/2010s-total-cities-and-towns.html#ds

# CSV File Layout:
    # https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2018/sub-est2018.pdf

In [18]:
usa = pd.read_csv(
    urlopen('https://www2.census.gov/programs-surveys/popest/datasets/2010-2018/cities/totals/sub-est2018_all.csv'),
    encoding='latin-1',
    dtype={'STATE': 'str', 'COUNTY': 'str', 'PLACE': 'str'}
)
virginia = pd.read_csv(
    urlopen('https://www2.census.gov/programs-surveys/popest/datasets/2010-2018/cities/totals/sub-est2018_51.csv'),
    encoding='latin-1',
    dtype={'STATE': 'str', 'COUNTY': 'str', 'PLACE': 'str'}
)

In [17]:
usa.shape

(81436, 21)

In [19]:
virginia.head()

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,FUNCSTAT,NAME,STNAME,...,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018
0,40,51,000,00000,0,0,0,A,Virginia,Virginia,...,8001055,8023680,8100469,8185229,8253053,8312076,8362907,8410946,8465207,8517685
1,162,51,000,00148,0,0,0,A,Abingdon town,Virginia,...,8206,8207,8161,8155,8131,8093,8040,8034,7985,7963
2,162,51,000,00180,0,0,0,A,Accomac town,Virginia,...,509,502,508,508,497,498,503,494,493,487
3,162,51,000,00724,0,0,0,A,Alberta town,Virginia,...,298,298,293,291,289,286,284,281,280,275
4,162,51,000,01000,0,0,0,A,Alexandria city,Virginia,...,140008,140740,144220,147314,149674,151431,153863,157045,159654,160530

In [20]:
virginia.SUMLEV.unique()

array([ 40, 162,  50, 157], dtype=int64)

In [21]:
usa.SUMLEV.unique()

array([ 40, 162,  50, 157, 170, 172,  61,  71], dtype=int64)

In [24]:
for sl in usa.SUMLEV.unique():
    print((sl,usa.SUMLEV[usa['SUMLEV']==sl].count()))
# 40 state
# 50 county (or independent city a la Virginia)
# 162 incorporated city or town
# 157 incorporated city or town    INTERSECT   a (county or independent city)
# 172 ??? mostly in Kentucky
# 170 ???

(40, 51)
(162, 19495)
(50, 3142)
(157, 23709)
(170, 8)
(172, 115)
(61, 21071)
(71, 13845)

In [29]:
usa[usa.SUMLEV==61]

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,FUNCSTAT,NAME,STNAME,...,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018
4660,61,09,001,00000,4720,0,1,A,Bethel town,Connecticut,...,18579,18626,18911,19140,19237,19308,19450,19617,19639,19714
4661,61,09,001,00000,8070,0,0,C,Bridgeport town,Connecticut,...,144239,144858,146131,147097,147726,147892,147460,146353,145408,144900
4663,61,09,001,00000,8980,0,1,A,Brookfield town,Connecticut,...,16443,16465,16599,16763,16816,16989,17052,17054,17016,17002
4664,61,09,001,00000,18500,0,0,C,Danbury town,Connecticut,...,80907,81324,82096,82793,83606,83722,84252,84995,84680,84730
4666,61,09,001,00000,18850,0,1,A,Darien town,Connecticut,...,20732,20768,20960,21146,21347,21680,21765,21790,21742,21753
4667,61,09,001,00000,23890,0,1,A,Easton town,Connecticut,...,7490,7501,7556,7604,7608,7617,7601,7561,7528,7517
4668,61,09,001,00000,26620,0,1,A,Fairfield town,Connecticut,...,59404,59705,60336,60783,60999,61342,61387,61431,61913,61952
4669,61,09,001,00000,33620,0,1,A,Greenwich town,Connecticut,...,61206,61322,61900,62368,62472,62589,62622,62537,62402,62727
4670,61,09,001,00000,48620,0,1,A,Monroe town,Connecticut,...,19477,19500,19649,19777,19776,19786,19723,19594,19502,19470
4671,61,09,001,00000,50580,0,1,A,New Canaan town,Connecticut,...,19748,19776,19960,20134,20195,20284,20333,20293,20231,20213
4672,61,09,001,00000,50860,0,1,A,New Fairfield town,Connecticut,...,13867,13888,14004,14094,14104,14093,14053,13980,13920,13877
4673,61,09,001,00000,52980,0,0,A,Newtown town,Connecticut,...,27574,27613,27827,28083,28081,27957,27928,27847,27753,27774
4676,61,09,001,00000,56060,0,0,C,Norwalk town,Connecticut,...,85623,85971,86619,87269,87743,88047,88287,88487,88399,89047
4678,61,09,001,00000,63480,0,1,A,Redding town,Connecticut,...,9151,9162,9240,9297,9298,9283,9269,9208,9160,9125
4679,61,09,001,00000,63970,0,1,A,Ridgefield town,Connecticut,...,24641,24677,24881,25058,25130,25138,25157,25045,25024,25008
4680,61,09,001,00000,68170,0,0,C,Shelton town,Connecticut,...,39562,39613,39954,40246,40930,41162,41109,41261,41108,41097
4682,61,09,001,00000,68310,0,1,A,Sherman town,Connecticut,...,3581,3587,3619,3649,3664,3661,3653,3638,3619,3614
4683,61,09,001,00000,73070,0,0,C,Stamford town,Connecticut,...,122633,122782,123980,125054,126318,127974,128407,129042,129951,129775
4685,61,09,001,00000,74190,0,1,A,Stratford town,Connecticut,...,51381,51443,51838,52154,52135,52690,52532,52258,51981,51967
4686,61,09,001,00000,77200,0,1,A,Trumbull town,Connecticut,...,36011,36050,36299,36520,36516,36611,36435,36114,35930,35802
4687,61,09,001,00000,83430,0,1,A,Weston town,Connecticut,...,10179,10191,10284,10348,10355,10358,10345,10288,10262,10247
4688,61,09,001,00000,83500,0,1,A,Westport town,Connecticut,...,26389,26437,26770,27100,27319,27527,27827,27861,27836,28115
4689,61,09,001,00000,86370,0,1,A,Wilton town,Connecticut,...,18047,18071,18484,18620,18616,18645,18654,18548,18453,18397
4695,61,09,003,00000,2060,0,1,A,Avon town,Connecticut,...,18091,18156,18197,18284,18328,18375,18344,18345,18307,18302
4696,61,09,003,00000,4300,0,1,A,Berlin town,Connecticut,...,19873,19900,20170,20484,20566,20608,20559,20533,20457,20432
4697,61,09,003,00000,5910,0,1,A,Bloomfield town,Connecticut,...,20480,20490,20539,20628,20615,20786,20713,20573,21352,21301
4698,61,09,003,00000,8490,0,0,C,Bristol town,Connecticut,...,60474,60478,60569,60635,60542,60576,60513,60289,60110,60032
4700,61,09,003,00000,10100,0,1,A,Burlington town,Connecticut,...,9301,9315,9385,9428,9467,9560,9605,9609,9620,9665
4701,61,09,003,00000,12270,0,1,A,Canton town,Connecticut,...,10292,10297,10325,10354,10347,10349,10336,10312,10276,10270
4702,61,09,003,00000,22070,0,1,A,East Granby town,Connecticut,...,5148,5158,5164,5184,5200,5204,5190,5169,5155,5147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81150,61,55,141,00000,7650,0,0,F,Biron village,Wisconsin,...,837,837,832,827,819,808,801,793,788,783
81152,61,55,141,00000,12275,0,1,A,Cameron town,Wisconsin,...,501,504,504,501,499,496,492,488,488,487
81153,61,55,141,00000,12775,0,1,A,Cary town,Wisconsin,...,424,424,424,422,420,417,412,409,408,406
81154,61,55,141,00000,17525,0,1,A,Cranmoor town,Wisconsin,...,168,168,167,167,165,163,162,161,160,159
81155,61,55,141,00000,20075,0,1,A,Dexter town,Wisconsin,...,359,361,362,360,357,353,351,352,349,347
81156,61,55,141,00000,30125,0,1,A,Grand Rapids town,Wisconsin,...,7639,7653,7657,7620,7578,7518,7482,7434,7427,7432
81157,61,55,141,00000,32575,0,1,A,Hansen town,Wisconsin,...,696,696,694,687,682,674,671,665,660,663
81158,61,55,141,00000,34250,0,0,F,Hewitt village,Wisconsin,...,826,826,826,818,820,813,804,797,794,789
81160,61,55,141,00000,34675,0,1,A,Hiles town,Wisconsin,...,167,167,166,166,164,164,164,163,162,161
81161,61,55,141,00000,44550,0,1,A,Lincoln town,Wisconsin,...,1571,1574,1568,1572,1579,1564,1559,1549,1544,1537
81162,61,55,141,00000,49675,0,0,F,Marshfield city,Wisconsin,...,18197,18199,18123,18005,17849,17803,17723,17623,17513,17435
81164,61,55,141,00000,49700,0,1,A,Marshfield town,Wisconsin,...,790,793,795,798,799,800,798,792,793,794
81165,61,55,141,00000,51875,0,0,F,Milladore village,Wisconsin,...,276,276,275,276,276,273,271,268,267,263
81167,61,55,141,00000,51900,0,1,A,Milladore town,Wisconsin,...,690,690,688,684,678,671,670,665,664,663
81168,61,55,141,00000,55875,0,0,F,Nekoosa city,Wisconsin,...,2580,2580,2566,2547,2525,2495,2470,2446,2430,2448
81170,61,55,141,00000,63100,0,0,F,Pittsville city,Wisconsin,...,874,874,871,866,866,854,849,840,839,834
81172,61,55,141,00000,64175,0,0,F,Port Edwards village,Wisconsin,...,1818,1818,1784,1782,1760,1751,1738,1751,1773,1777
81174,61,55,141,00000,64200,0,1,A,Port Edwards town,Wisconsin,...,1427,1427,1420,1416,1405,1387,1380,1369,1362,1359
81175,61,55,141,00000,67000,0,1,A,Remington town,Wisconsin,...,268,268,267,266,262,259,257,255,252,251
81176,61,55,141,00000,67500,0,1,A,Richfield town,Wisconsin,...,1628,1631,1625,1631,1637,1609,1595,1597,1579,1570
81177,61,55,141,00000,68625,0,1,A,Rock town,Wisconsin,...,855,884,956,1010,1121,1264,1440,1591,1765,1930
81178,61,55,141,00000,70000,0,0,F,Rudolph village,Wisconsin,...,439,439,437,433,431,429,427,424,424,422
81180,61,55,141,00000,70025,0,1,A,Rudolph town,Wisconsin,...,1026,1026,1022,1017,1006,995,991,992,985,977
81181,61,55,141,00000,71600,0,1,A,Saratoga town,Wisconsin,...,5142,5145,5124,5104,5090,5045,5016,4983,4968,4962
81182,61,55,141,00000,72575,0,1,A,Seneca town,Wisconsin,...,1119,1119,1120,1116,1105,1095,1083,1075,1070,1068
81183,61,55,141,00000,73475,0,1,A,Sherry town,Wisconsin,...,803,803,818,818,814,802,801,794,791,791
81184,61,55,141,00000,73900,0,1,A,Sigel town,Wisconsin,...,1051,1051,1047,1044,1037,1030,1026,1021,1018,1014
81185,61,55,141,00000,82650,0,0,F,Vesper village,Wisconsin,...,584,584,582,576,574,570,563,560,556,553
81187,61,55,141,00000,88200,0,0,F,Wisconsin Rapids city,Wisconsin,...,18379,18379,18323,18196,18030,17961,17860,17898,17804,17696
81189,61,55,141,00000,88575,0,1,A,Wood town,Wisconsin,...,790,790,787,783,776,765,764,760,758,759

The resulting data frame has a lot of information that we don’t need and can be discarded. According to the <a href="https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2018/sub-est2018.pdf"> file layout description</a>, the data is summarized at the nation, state, county and place levels according to the SUMLEV column. Since we’re only interested in the population for each state we can just filter the rows with SUMLEV ‘40’, but wanted to show you how to use the aggregate feature of Pandas’ DataFrames, so we’ll take the data summarized at the count level (SUMLEV ‘50’), then we’ll group by state, and sum the population estimates.

In [30]:
usa_county = usa[usa.SUMLEV == 50]
usa_state = usa_county.groupby(['STATE']).sum()

# Alternatively we could have just taken the summary rows for the states

# sub_est_2012_df_by_state = sub_est_2012_df[sub_est_2012_df.SUMLEV == 40]

In [41]:
usa_state
# the indiscriminate SUM probably summed a bunch of categorical/other numbers that shouldn't have been added
        # e.g. SUMLEV !!
    # but we won't worry about that

,SUMLEV,COUSUB,CONCIT,PRIMGEO_FLAG,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018
STATE,,,,,,,,,,,,,,
01,3350,0,0,0,4780138,4785448,4798834,4815564,4830460,4842481,4853160,4864745,4875120,4887871
02,1450,0,0,4,710249,713906,722038,730399,737045,736307,737547,741504,739786,737438
04,750,0,0,0,6392288,6407774,6473497,6556629,6634999,6733840,6833596,6945452,7048876,7171646
05,3750,0,0,0,2916028,2921978,2940407,2952109,2959549,2967726,2978407,2990410,3002997,3013825
06,2900,0,0,3,37254523,37320903,37641823,37960782,38280824,38625139,38953142,39209127,39399349,39557045
08,3200,0,0,0,5029316,5048281,5121771,5193721,5270482,5351218,5452107,5540921,5615902,5695564
09,400,0,0,0,3574147,3579125,3588023,3594395,3594915,3594783,3587509,3578674,3573880,3572665
10,150,0,0,0,897934,899595,907316,915188,923638,932596,941413,949216,957078,967171
11,50,0,0,0,601766,605085,619602,634725,650431,662513,675254,686575,695691,702455
12,3350,0,0,0,18804580,18845785,19093352,19326230,19563166,19860330,20224249,20629982,20976812,21299325
13,7950,0,0,0,9688709,9711810,9801578,9901496,9973326,10069001,10181111,10304763,10413055,10519475
15,250,0,0,4,1360307,1363963,1379252,1394905,1408453,1414862,1422484,1428105,1424203,1420491
16,2200,0,0,0,1567657,1570773,1583828,1595441,1611530,1631479,1651523,1682930,1718904,1754208
17,5100,0,0,0,12831572,12840762,12867291,12884119,12898269,12888962,12864342,12826895,12786196,12741080
18,4600,0,0,0,6484061,6490436,6516045,6537640,6568367,6593533,6608296,6633344,6660082,6691878
19,4950,0,0,0,3046872,3050767,3066054,3076097,3093078,3109504,3121460,3131785,3143637,3156145
20,5250,0,0,0,2853126,2858213,2869035,2885361,2893510,2900896,2909502,2911263,2910689,2911505
21,6000,0,0,1,4339333,4348200,4369488,4386381,4404817,4414483,4425999,4438229,4453874,4468402
22,3200,0,0,5,4533485,4544532,4575184,4600814,4624577,4644204,4664851,4678215,4670818,4659978
23,800,0,0,0,1328369,1327632,1328150,1327691,1328196,1330760,1328484,1331370,1335063,1338404
24,1200,0,0,2,5773798,5788642,5838991,5887072,5923704,5958165,5986717,6004692,6024891,6042718
25,700,0,0,0,6547790,6566431,6613149,6663158,6713944,6763652,6795891,6826022,6863246,6902149
26,4150,0,0,0,9884117,9877535,9881521,9896930,9913349,9930589,9932573,9951890,9976447,9995915
27,4350,0,0,0,5303925,5310843,5345668,5376550,5413693,5451522,5482503,5523409,5568155,5611179
28,4100,0,0,0,2968118,2970536,2978470,2983767,2988797,2990623,2988693,2988298,2989663,2986530
29,5750,0,0,0,5988952,5995976,6009641,6024081,6040658,6056293,6071745,6087203,6108612,6126452
30,2800,0,0,0,989409,990722,997221,1003754,1013564,1021891,1030503,1040863,1053090,1062305
31,4650,0,0,2,1826305,1829536,1840538,1853323,1865414,1879522,1891507,1905924,1917575,1929268
32,850,0,0,7,2700679,2702464,2712799,2744566,2776972,2819012,2868666,2919772,2972405,3034392
33,500,0,0,0,1316464,1316777,1319815,1323962,1326408,1333223,1336294,1342373,1349767,1356458
34,1050,0,0,0,8791962,8799624,8827783,8845483,8858362,8866780,8870869,8874516,8888543,8908520
35,1650,0,0,1,2059180,2064588,2080395,2087549,2092792,2090342,2090211,2092789,2093395,2095428
36,3100,0,0,0,19378124,19400080,19498514,19574549,19628043,19656330,19661411,19641589,19590719,19542209
37,5000,0,0,2,9535736,9574293,9656754,9749123,9843599,9933944,10033079,10156679,10270800,10383620
38,2650,0,0,0,672576,674710,685136,701116,721999,737382,754022,754353,755176,760077
39,4400,0,0,0,11536757,11539327,11543463,11548369,11576576,11602973,11617850,11635003,11664129,11689442
40,3850,0,0,0,3751583,3759632,3787821,3818600,3853205,3878367,3909831,3926769,3932640,3943079
41,1800,0,0,0,3831075,3837532,3871728,3899118,3922908,3964106,4016918,4091404,4146592,4190713
42,3350,0,0,0,12702873,12711158,12744583,12766827,12776621,12789101,12785759,12783538,12790447,12807060
44,250,0,0,0,1052957,1053938,1053536,1054601,1055122,1056017,1056173,1057063,1056486,1057315
45,2300,0,0,0,4625381,4635656,4671422,4717112,4764153,4823793,4892253,4958235,5021219,5084127
46,3300,0,0,0,814198,816165,823484,833496,842270,849088,853933,862890,873286,882235
47,4750,0,0,0,6346286,6355301,6397410,6451281,6493432,6540826,6590808,6645011,6708794,6770010
48,12700,0,0,10,25146114,25242679,25646227,26089620,26489464,26977142,27486814,27937492,28322717,28701845
49,1450,0,0,0,2763891,2775334,2814216,2853467,2897927,2937399,2982497,3042613,3103118,3161105
50,700,0,0,0,625744,625880,626979,626063,626212,625218,625197,623644,624525,626299
51,6650,0,0,20,8001055,8023680,8100469,8185229,8253053,8312076,8362907,8410946,8465207,8517685
53,1950,0,0,0,6724540,6742902,6821655,6892876,6962906,7052439,7163543,7294680,7425432,7535591
54,2750,0,0,0,1853001,1854214,1856074,1856764,1853873,1849467,1841996,1830929,1817048,1805832
55,3600,0,0,0,5687282,5690479,5704755,5719855,5736952,5751974,5761406,5772958,5792051,5813568
56,1150,0,0,0,563773,564483,567224,576270,582123,582548,585668,584290,578934,577737

In [35]:
missing_state_ids=[3,7,14,43,52]

In [40]:
usa[usa.STATE==52]

Empty DataFrame
Columns: [SUMLEV, STATE, COUNTY, PLACE, COUSUB, CONCIT, PRIMGEO_FLAG, FUNCSTAT, NAME, STNAME, CENSUS2010POP, ESTIMATESBASE2010, POPESTIMATE2010, POPESTIMATE2011, POPESTIMATE2012, POPESTIMATE2013, POPESTIMATE2014, POPESTIMATE2015, POPESTIMATE2016, POPESTIMATE2017, POPESTIMATE2018]
Index: []

[0 rows x 21 columns]

If you see the table, the states are referenced using their ANSI codes. We can augment the table to include the state names and abbreviations by merging with <a href="http://www.census.gov/geo/reference/ansi_statetables.html"> another resource</a> from the Geography section of the US Census Bureau site. We use read_csv Pandas function making sure that we use the pipe character (|) as separator.

In [43]:
# Taken from http://www.census.gov/geo/reference/ansi_statetables.html

state = pd.read_csv(urlopen('https://www2.census.gov/geo/docs/reference/state.txt'), sep='|', dtype={'STATE': 'str'})
    # old link was at http://www.census.gov/geo/reference/docs/state.txt

In [44]:
state

   STATE STUSAB                   STATE_NAME  STATENS
0     01     AL                      Alabama  1779775
1     02     AK                       Alaska  1785533
2     04     AZ                      Arizona  1779777
3     05     AR                     Arkansas    68085
4     06     CA                   California  1779778
5     08     CO                     Colorado  1779779
6     09     CT                  Connecticut  1779780
7     10     DE                     Delaware  1779781
8     11     DC         District of Columbia  1702382
9     12     FL                      Florida   294478
10    13     GA                      Georgia  1705317
11    15     HI                       Hawaii  1779782
12    16     ID                        Idaho  1779783
13    17     IL                     Illinois  1779784
14    18     IN                      Indiana   448508
15    19     IA                         Iowa  1779785
16    20     KS                       Kansas   481813
17    21     KY                     Kentucky  1779786
18    22     LA                    Louisiana  1629543
19    23     ME                        Maine  1779787
20    24     MD                     Maryland  1714934
21    25     MA                Massachusetts   606926
22    26     MI                     Michigan  1779789
23    27     MN                    Minnesota   662849
24    28     MS                  Mississippi  1779790
25    29     MO                     Missouri  1779791
26    30     MT                      Montana   767982
27    31     NE                     Nebraska  1779792
28    32     NV                       Nevada  1779793
29    33     NH                New Hampshire  1779794
30    34     NJ                   New Jersey  1779795
31    35     NM                   New Mexico   897535
32    36     NY                     New York  1779796
33    37     NC               North Carolina  1027616
34    38     ND                 North Dakota  1779797
35    39     OH                         Ohio  1085497
36    40     OK                     Oklahoma  1102857
37    41     OR                       Oregon  1155107
38    42     PA                 Pennsylvania  1779798
39    44     RI                 Rhode Island  1219835
40    45     SC               South Carolina  1779799
41    46     SD                 South Dakota  1785534
42    47     TN                    Tennessee  1325873
43    48     TX                        Texas  1779801
44    49     UT                         Utah  1455989
45    50     VT                      Vermont  1779802
46    51     VA                     Virginia  1779803
47    53     WA                   Washington  1779804
48    54     WV                West Virginia  1779805
49    55     WI                    Wisconsin  1779806
50    56     WY                      Wyoming  1779807
51    60     AS               American Samoa  1802701
52    66     GU                         Guam  1802705
53    69     MP     Northern Mariana Islands  1779809
54    72     PR                  Puerto Rico  1779808
55    74     UM  U.S. Minor Outlying Islands  1878752
56    78     VI          U.S. Virgin Islands  1802710

In [45]:
state.drop(
    ['STATENS'],
    inplace=True, axis=1
)    # discard the Geographic Names Information System Identifier (GNISID)

In [46]:
usa_state = pd.merge(usa_state, state, left_index=True, right_on='STATE')
usa_state.drop(
    ['SUMLEV', 'COUSUB', 'CONCIT', 'ESTIMATESBASE2010', 'POPESTIMATE2010', 'POPESTIMATE2011'],
    inplace=True, axis=1
)

In [47]:
usa_state.head()

,PRIMGEO_FLAG,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,STATE,STUSAB,STATE_NAME
0,0,4815564,4830460,4842481,4853160,4864745,4875120,4887871,01,AL,Alabama
1,4,730399,737045,736307,737547,741504,739786,737438,02,AK,Alaska
2,0,6556629,6634999,6733840,6833596,6945452,7048876,7171646,04,AZ,Arizona
3,0,2952109,2959549,2967726,2978407,2990410,3002997,3013825,05,AR,Arkansas
4,3,37960782,38280824,38625139,38953142,39209127,39399349,39557045,06,CA,California

We're also interested in plotting the information about the age and sex of the people, and for that we can use the <a href="https://www2.census.gov/programs-surveys/popest/datasets/2010-2017/state/asrh/sc-est2017-agesex-civ.csv?#"> Annual Estimates of the Civilian Population by Single Year of Age and Sex</a>.

https://www.census.gov/newsroom/press-kits/2018/estimates-characteristics.html

In [50]:
ASC = pd.read_csv(
    urlopen('https://www2.census.gov/programs-surveys/popest/datasets/2010-2017/state/asrh/sc-est2017-agesex-civ.csv'),
    encoding='latin-1',
    dtype={'SUMLEV': 'str'}
)

# Layout: 
#https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2017/sc-est2017-agesex-civ.pdf?#

In [52]:
ASC

,SUMLEV,REGION,DIVISION,STATE,NAME,SEX,AGE,ESTBASE2010_CIV,POPEST2010_CIV,POPEST2011_CIV,POPEST2012_CIV,POPEST2013_CIV,POPEST2014_CIV,POPEST2015_CIV,POPEST2016_CIV,POPEST2017_CIV
0,010,0,0,0,United States,0,0,3944160,3951454,3962971,3926486,3931208,3954725,3984294,3955377,3939295
1,010,0,0,0,United States,0,1,3978090,3957695,3966056,3977264,3942441,3948689,3973189,4004017,3975252
2,010,0,0,0,United States,0,2,4096939,4090616,3970491,3978648,3991295,3958296,3965536,3990991,4021775
3,010,0,0,0,United States,0,3,4119051,4111682,4101643,3981321,3990699,4005424,3973376,3981326,4006755
4,010,0,0,0,United States,0,4,4063186,4077326,4121485,4111444,3992298,4003684,4019335,3987866,3995783
5,010,0,0,0,United States,0,5,4056872,4064480,4087056,4131048,4121794,4004373,4016658,4032787,4001318
6,010,0,0,0,United States,0,6,4066412,4072889,4074516,4096654,4141144,4133300,4016732,4029444,4045532
7,010,0,0,0,United States,0,7,4030594,4042967,4082870,4084201,4106863,4152751,4145829,4029700,4042379
8,010,0,0,0,United States,0,8,4046497,4025495,4052889,4092669,4094674,4118570,4165408,4158968,4042838
9,010,0,0,0,United States,0,9,4148369,4125317,4035461,4062842,4103296,4106389,4131317,4178605,4172171
10,010,0,0,0,United States,0,10,4172559,4186959,4135458,4045601,4073237,4115033,4119269,4144625,4191919
11,010,0,0,0,United States,0,11,4114443,4115452,4197307,4145939,4056173,4085016,4128022,4132611,4157962
12,010,0,0,0,United States,0,12,4106261,4113239,4126020,4208003,4156759,4067899,4097932,4141353,4145953
13,010,0,0,0,United States,0,13,4118055,4119585,4124131,4136655,4219019,4169022,4081296,4111886,4155315
14,010,0,0,0,United States,0,14,4166059,4145490,4131295,4135424,4148560,4232526,4183831,4096727,4127305
15,010,0,0,0,United States,0,15,4242946,4230902,4158739,4143882,4149009,4164225,4249635,4201611,4114560
16,010,0,0,0,United States,0,16,4316311,4313090,4247235,4174315,4160427,4167605,4184373,4270670,4222691
17,010,0,0,0,United States,0,17,4395196,4375125,4333695,4267210,4194548,4182890,4191286,4209213,4295168
18,010,0,0,0,United States,0,18,4482436,4474425,4386156,4344004,4276385,4207169,4195549,4204110,4219505
19,010,0,0,0,United States,0,19,4533403,4520730,4471152,4379461,4331693,4269945,4203370,4191372,4199586
20,010,0,0,0,United States,0,20,4452626,4501064,4536684,4485716,4389397,4347521,4288346,4221448,4210050
21,010,0,0,0,United States,0,21,4280148,4312385,4520006,4558777,4503115,4410393,4371852,4312907,4245917
22,010,0,0,0,United States,0,22,4188295,4207857,4335653,4546272,4584324,4530793,4442192,4403367,4344484
23,010,0,0,0,United States,0,23,4122832,4140397,4238098,4369165,4580390,4620678,4570125,4481373,4443317
24,010,0,0,0,United States,0,24,4176530,4170147,4172334,4272278,4403974,4618532,4662023,4609590,4521713
25,010,0,0,0,United States,0,25,4194785,4220626,4200558,4205359,4305470,4439961,4657791,4700193,4647331
26,010,0,0,0,United States,0,26,4090707,4098198,4248400,4231640,4237101,4339614,4478222,4694014,4737089
27,010,0,0,0,United States,0,27,4192055,4179511,4124900,4278443,4263138,4271627,4377996,4513850,4730444
28,010,0,0,0,United States,0,28,4164505,4195291,4203841,4152059,4306629,4295320,4307785,4411532,4547023
29,010,0,0,0,United States,0,29,4176622,4162951,4216972,4228441,4178046,4335946,4329382,4339031,4442645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13542,040,4,8,56,Wyoming,2,57,4059,4057,4095,4338,4351,4333,4140,4141,4121
13543,040,4,8,56,Wyoming,2,58,3807,3835,4015,4125,4316,4283,4286,4120,4067
13544,040,4,8,56,Wyoming,2,59,3704,3743,3777,4001,4078,4250,4211,4222,4068
13545,040,4,8,56,Wyoming,2,60,3537,3558,3724,3763,4013,3986,4213,4193,4163
13546,040,4,8,56,Wyoming,2,61,3249,3316,3495,3681,3709,3902,3928,4155,4135
13547,040,4,8,56,Wyoming,2,62,3319,3245,3262,3472,3635,3627,3819,3897,4128
13548,040,4,8,56,Wyoming,2,63,3227,3407,3218,3237,3452,3551,3564,3762,3870
13549,040,4,8,56,Wyoming,2,64,2358,2419,3347,3219,3249,3370,3469,3493,3705
13550,040,4,8,56,Wyoming,2,65,2564,2514,2370,3299,3205,3154,3295,3384,3420
13551,040,4,8,56,Wyoming,2,66,2414,2422,2477,2359,3236,3169,3087,3265,3367
13552,040,4,8,56,Wyoming,2,67,2363,2426,2391,2455,2302,3188,3139,3010,3224
13553,040,4,8,56,Wyoming,2,68,2125,2139,2384,2348,2394,2282,3166,3102,2978
13554,040,4,8,56,Wyoming,2,69,1957,1981,2123,2345,2321,2356,2250,3121,3083
13555,040,4,8,56,Wyoming,2,70,1877,1886,1935,2063,2274,2295,2303,2204,3048
13556,040,4,8,56,Wyoming,2,71,1744,1757,1858,1896,2031,2246,2256,2274,2154
13557,040,4,8,56,Wyoming,2,72,1699,1712,1726,1829,1837,1999,2191,2207,2206
13558,040,4,8,56,Wyoming,2,73,1603,1609,1666,1695,1789,1792,1946,2148,2145
13559,040,4,8,56,Wyoming,2,74,1550,1548,1563,1603,1644,1727,1729,1890,2086
13560,040,4,8,56,Wyoming,2,75,1509,1516,1515,1533,1571,1616,1703,1686,1849
13561,040,4,8,56,Wyoming,2,76,1377,1378,1459,1473,1478,1522,1583,1658,1644
13562,040,4,8,56,Wyoming,2,77,1304,1316,1357,1403,1425,1451,1475,1539,1618
13563,040,4,8,56,Wyoming,2,78,1344,1325,1256,1325,1355,1378,1422,1436,1485
13564,040,4,8,56,Wyoming,2,79,1262,1249,1277,1185,1245,1295,1292,1341,1368
13565,040,4,8,56,Wyoming,2,80,1189,1205,1199,1202,1124,1193,1241,1233,1276
13566,040,4,8,56,Wyoming,2,81,1175,1157,1149,1162,1164,1090,1143,1187,1189
13567,040,4,8,56,Wyoming,2,82,1102,1102,1107,1084,1105,1104,1034,1094,1124
13568,040,4,8,56,Wyoming,2,83,911,936,1026,1035,1000,1029,1030,960,1018
13569,040,4,8,56,Wyoming,2,84,894,883,880,1009,986,943,972,975,923
13570,040,4,8,56,Wyoming,2,85,5623,5644,5727,5854,6041,6248,6355,6473,6542
13571,040,4,8,56,Wyoming,2,999,275793,276163,277766,281774,284509,285076,286118,285727,283368

Once again, the table is summarized at many levels, but we're only interested in the information at the state level, so we filter out the unnecessary rows. We also do a little bit of processing to the STATE column so it can be used to merge with the state DataFrame.

In [51]:
ASC.shape

(13572, 16)

In [53]:
ASC = ASC[
    (ASC.SUMLEV == '040') &
    (ASC.SEX != 0) &
    (ASC.AGE != 999)
]
ASC.drop(
    ['SUMLEV', 'NAME', 'ESTBASE2010_CIV', 'POPEST2010_CIV', 'POPEST2011_CIV'],
    inplace=True, axis=1
)
ASC['STATE'] = ASC['STATE'].apply(lambda x: '%02d' % (x,))

C:\Users\rek\Anaconda3\envs\dale_pyjsviz\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)
C:\Users\rek\Anaconda3\envs\dale_pyjsviz\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [54]:
ASC.shape

(8772, 11)

What we need to do is group the rows by state, region, division and sex, and sum across all ages. Afterwards, we augment the result with the names and abbreviations of the states.

In [55]:
ASC_sex = ASC.groupby(
                ['STATE', 'REGION', 'DIVISION', 'SEX'], as_index=False)[['POPEST2012_CIV']].sum()
ASC_sex = pd.merge(ASC_sex, state, left_on='STATE', right_on='STATE')

In [57]:
ASC_sex
# 1=male, 2=female

    STATE  REGION  DIVISION  SEX  POPEST2012_CIV STUSAB            STATE_NAME
0      01       3         6    1         2321602     AL               Alabama
1      01       3         6    2         2476692     AL               Alabama
2      02       4         9    1          363179     AK                Alaska
3      02       4         9    2          346665     AK                Alaska
4      04       4         8    1         3237014     AZ               Arizona
5      04       4         8    2         3287198     AZ               Arizona
6      05       3         7    1         1442917     AR              Arkansas
7      05       3         7    2         1499735     AR              Arkansas
8      06       4         9    1        18750841     CA            California
9      06       4         9    2        19115142     CA            California
10     08       4         8    1         2570087     CO              Colorado
11     08       4         8    2         2581514     CO              Colorado
12     09       1         1    1         1745840     CT           Connecticut
13     09       1         1    2         1844327     CT           Connecticut
14     10       3         5    1          440880     DE              Delaware
15     10       3         5    2          472116     DE              Delaware
16     11       3         5    1          298512     DC  District of Columbia
17     11       3         5    2          334063     DC  District of Columbia
18     12       3         5    1         9398820     FL               Florida
19     12       3         5    2         9874760     FL               Florida
20     13       3         5    1         4784593     GA               Georgia
21     13       3         5    2         5061649     GA               Georgia
22     15       4         9    1          662022     HI                Hawaii
23     15       4         9    2          687669     HI                Hawaii
24     16       4         8    1          795350     ID                 Idaho
25     16       4         8    2          795553     ID                 Idaho
26     17       2         3    1         6295613     IL              Illinois
27     17       2         3    2         6554041     IL              Illinois
28     18       2         3    1         3214891     IN               Indiana
29     18       2         3    2         3317127     IN               Indiana
..    ...     ...       ...  ...             ...    ...                   ...
72     40       3         7    1         1870259     OK              Oklahoma
73     40       3         7    2         1923031     OK              Oklahoma
74     41       4         9    1         1924807     OR                Oregon
75     41       4         9    2         1966476     OR                Oregon
76     42       1         2    1         6229133     PA          Pennsylvania
77     42       1         2    2         6531626     PA          Pennsylvania
78     44       1         1    1          506230     RI          Rhode Island
79     44       1         1    2          542588     RI          Rhode Island
80     45       3         5    1         2257021     SC        South Carolina
81     45       3         5    2         2418366     SC        South Carolina
82     46       2         4    1          414903     SD          South Dakota
83     46       2         4    2          413709     SD          South Dakota
84     47       3         6    1         3122878     TN             Tennessee
85     47       3         6    2         3303247     TN             Tennessee
86     48       3         7    1        12827774     TX                 Texas
87     48       3         7    2        13116090     TX                 Texas
88     49       4         8    1         1429882     UT                  Utah
89     49       4         8    2         1418546     UT                  Utah
90     50       1         1    1          307910     VT               Vermont
91     50       1         1    2          317094     VT               Vermont
92     51       3         5    1         3934913     VA              Virginia
93     51       3         5    2         4143224     VA              Virginia
94     53       4         9    1         3395104     WA            Washington
95     53       4         9    2         3449287     WA            Washington
96     54       3         5    1          914775     WV         West Virginia
97     54       3         5    2          939045     WV         West Virginia
98     55       2         3    1         2837962     WI             Wisconsin
99     55       2         3    2         2879749     WI             Wisconsin
100    56       4         8    1          291693     WY               Wyoming
101    56       4         8    2          281774     WY               Wyoming

[102 rows x 7 columns]

For the age information, we group by state, region, division and age and we sum across all sexes. If you see the result, you'll notice that there's a row for each year. This is pretty useful for analysis, but it can be problematic to plot, so we're going to group the rows according to age buckets of 20 years. Once again, we add the state information at the end.

In [58]:
ASC_age = ASC.groupby(['STATE', 'REGION', 'DIVISION', 'AGE'], as_index=False)[['POPEST2012_CIV']].sum()

In [62]:
ASC_age.tail()

     STATE  REGION  DIVISION  AGE  POPEST2012_CIV
4381    56       4         8   81            2057
4382    56       4         8   82            1973
4383    56       4         8   83            1849
4384    56       4         8   84            1752
4385    56       4         8   85            9244

In [63]:
age_buckets = pd.cut(ASC_age.AGE, range(0,100,20))

In [64]:
print(ASC_age.shape)
print(age_buckets.shape)

(4386, 5)
(4386,)

In [66]:
age_buckets.unique()
# Interval categories !!!!

[NaN, (0.0, 20.0], (20.0, 40.0], (40.0, 60.0], (60.0, 80.0]]
Categories (4, interval[int64]): [(0, 20] < (20, 40] < (40, 60] < (60, 80]]

In [67]:
ASC_age2 = ASC_age.groupby(['STATE', 'REGION', 'DIVISION', age_buckets], as_index=False)['POPEST2012_CIV'].sum()
ASC_age2 = pd.merge(ASC_age2, state, left_on='STATE', right_on='STATE')

In [72]:
print(ASC_age2.POPEST2012_CIV.isnull().sum(),ASC_age2.POPEST2012_CIV.isnull().count())
# okay 97% of the entries are null. This isn't good

# but actually it looks like their are four good numbers for each state.
    # corresponding to one for each of the four buckets
        # i guess the population over 80yo will be ignored???

7140 7344

In [73]:
ASC_age2[~ASC_age2.POPEST2012_CIV.isnull()]

     STATE  REGION  DIVISION  POPEST2012_CIV STUSAB     STATE_NAME
92      01       3         6       1258478.0     AL        Alabama
93      01       3         6       1242898.0     AL        Alabama
94      01       3         6       1312320.0     AL        Alabama
95      01       3         6        776330.0     AL        Alabama
284     02       4         9        205739.0     AK         Alaska
285     02       4         9        195964.0     AK         Alaska
286     02       4         9        203472.0     AK         Alaska
287     02       4         9         83460.0     AK         Alaska
424     04       4         8       1803838.0     AZ        Arizona
425     04       4         8       1729862.0     AZ        Arizona
426     04       4         8       1643740.0     AZ        Arizona
427     04       4         8       1050966.0     AZ        Arizona
528     05       3         7        793263.0     AR       Arkansas
529     05       3         7        760156.0     AR       Arkansas
530     05       3         7        771993.0     AR       Arkansas
531     05       3         7        481513.0     AR       Arkansas
716     06       4         9      10345998.0     CA     California
717     06       4         9      10759770.0     CA     California
718     06       4         9      10120587.0     CA     California
719     06       4         9       5015226.0     CA     California
856     08       4         8       1378973.0     CO       Colorado
857     08       4         8       1443200.0     CO       Colorado
858     08       4         8       1422954.0     CO       Colorado
859     08       4         8        707263.0     CO       Colorado
864     09       1         1        918649.0     CT    Connecticut
865     09       1         1        861447.0     CT    Connecticut
866     09       1         1       1071841.0     CT    Connecticut
867     09       1         1        553128.0     CT    Connecticut
1096    10       3         5        233093.0     DE       Delaware
1097    10       3         5        230136.0     DE       Delaware
...    ...     ...       ...             ...    ...            ...
6290    48       3         7       6672075.0     TX          Texas
6291    48       3         7       3222631.0     TX          Texas
6472    49       4         8        968190.0     UT           Utah
6473    49       4         8        861889.0     UT           Utah
6474    49       4         8        604973.0     UT           Utah
6475    49       4         8        302583.0     UT           Utah
6480    50       1         1        151734.0     VT        Vermont
6481    50       1         1        145124.0     VT        Vermont
6482    50       1         1        189127.0     VT        Vermont
6483    50       1         1        109499.0     VT        Vermont
6712    51       3         5       2100948.0     VA       Virginia
6713    51       3         5       2156140.0     VA       Virginia
6714    51       3         5       2290362.0     VA       Virginia
6715    51       3         5       1193485.0     VA       Virginia
6908    53       4         9       1766750.0     WA     Washington
6909    53       4         9       1860762.0     WA     Washington
6910    53       4         9       1902324.0     WA     Washington
6911    53       4         9       1017389.0     WA     Washington
7000    54       3         5        436024.0     WV  West Virginia
7001    54       3         5        453600.0     WV  West Virginia
7002    54       3         5        527591.0     WV  West Virginia
7003    54       3         5        345305.0     WV  West Virginia
7100    55       2         3       1499104.0     WI      Wisconsin
7101    55       2         3       1437620.0     WI      Wisconsin
7102    55       2         3       1625224.0     WI      Wisconsin
7103    55       2         3        873483.0     WI      Wisconsin
7336    56       4         8        152605.0     WY        Wyoming
7337    56       4         8        153288.0     WY        Wyoming
7338    56       4         8        156430.0     WY        Wyoming
7339    56       4         8         86878.0     WY        Wyoming

[204 rows x 6 columns]

We also need information about regions and divisions, but since the dataset is small, we'll build the dictionaries by hand.

In [75]:
region_codes = {
    0: 'United States Total',
    1: 'Northeast',
    2: 'Midwest',
    3: 'South',
    4: 'West'
}
division_codes = {
    0: 'United States Total',
    1: 'New England',
    2: 'Middle Atlantic',
    3: 'East North Central',
    4: 'West North Central',
    5: 'South Atlantic',
    6: 'East South Central',
    7: 'West South Central',
    8: 'Mountain',
    9: 'Pacific'
}

# Part 1 - Embedding D3.js

<a href="http://d3js.org"> D3.js</a> is an incredibly flexible JavaScript chart library. Although it is primarily used to plot data, it can be used to draw arbitrary graphics and animations.

Let's build a column chart of the five most populated states in the USA. IPython Notebooks are regular web pages so in order to use any JavaScript library in it, we need to load the necessary requirements. IPython Notebook uses <a href="http://requirejs.org"> RequireJS </a> to load its own requirements, so we can make use of it with the %%javascript cell magic to load external dependencies.

In all the examples of this notebook we'll load the libraries from <a href="http://cdnjs.com">cdnjs.com</a>, so to declare the requirement of D3.js we do

In [76]:
%%javascript
require.config({
    paths: {
        d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min'
    }
});

Now we'll make use of the `display` function and `HTML` from the IPython Notebook [API](http://ipython.org/ipython-doc/2/api/generated/IPython.core.display.html#module-IPython.core.display) to render HTML content within the notebook itself. We're declaring styles to change the look and feel of the plots, and we define a new `div` with id `"chart_d3"` that the library is going to use as the target of the plot.

In [77]:
display(HTML("""
<style>
.bar {
  fill: steelblue;
}
.bar:hover {
  fill: brown;
}
.axis {
  font: 10px sans-serif;
}
.axis path,
.axis line {
  fill: none;
  stroke: #000;
}
.x.axis path {
  display: none;
}
</style>
<div id="chart_d3"/>
"""))

Next, we define a template with the JavaScript code that is going to render the chart. Notice that we iterate over the \"data\" parameter to populate the \"data\" variable in JavaScript. Afterwards, we use the `display` method once again to force the execution of the JavaScript code, which renders the chart on the target div.

In [80]:
usa_state.head()

,PRIMGEO_FLAG,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,STATE,STUSAB,STATE_NAME
0,0,4815564,4830460,4842481,4853160,4864745,4875120,4887871,01,AL,Alabama
1,4,730399,737045,736307,737547,741504,739786,737438,02,AK,Alaska
2,0,6556629,6634999,6733840,6833596,6945452,7048876,7171646,04,AZ,Arizona
3,0,2952109,2959549,2967726,2978407,2990410,3002997,3013825,05,AR,Arkansas
4,3,37960782,38280824,38625139,38953142,39209127,39399349,39557045,06,CA,California

In [88]:
sub_est_2012_df_by_state_template = jinja2.Template(
"""
// Based on http://bl.ocks.org/mbostock/3885304

require(["d3"], function(d3) {
    var data = []

    {% for row in data %}
    data.push({ 'state': '{{ row[11] }}', 'population': {{ row[3] }} });
    {% endfor %}

    d3.select("#chart_d3 svg").remove()

    var margin = {top: 20, right: 20, bottom: 30, left: 40},
        width = 800 - margin.left - margin.right,
        height = 400 - margin.top - margin.bottom;

    var x = d3.scale.ordinal()
        .rangeRoundBands([0, width], .25);

    var y = d3.scale.linear()
        .range([height, 0]);

    var xAxis = d3.svg.axis()
        .scale(x)
        .orient("bottom");

    var yAxis = d3.svg.axis()
        .scale(y)
        .orient("left")
        .ticks(10)
        .tickFormat(d3.format('.1s'));
        
    var svg = d3.select("#chart_d3").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

    x.domain(data.map(function(d) { return d.state; }));
    y.domain([0, d3.max(data, function(d) { return d.population; })]);

    svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(xAxis);

    svg.append("g")
        .attr("class", "y axis")
        .call(yAxis)
        .append("text")
        .attr("transform", "rotate(-90)")
        .attr("y", 6)
        .attr("dy", ".71em")
        .style("text-anchor", "end")
        .text("Population");

    svg.selectAll(".bar")
        .data(data)
        .enter().append("rect")
        .attr("class", "bar")
        .attr("x", function(d) { return x(d.state); })
        .attr("width", x.rangeBand())
        .attr("y", function(d) { return y(d.population); })
        .attr("height", function(d) { return height - y(d.population); });
});
"""
)
display(Javascript(sub_est_2012_df_by_state_template.render(
    data=usa_state.sort_values(['POPESTIMATE2012'], ascending=False)[:5].itertuples()))
)

In [86]:
result=usa_state.sort_values(['POPESTIMATE2012'], ascending=False)[:5].itertuples()
list(result)

[Pandas(Index=4, PRIMGEO_FLAG=3, POPESTIMATE2012=37960782, POPESTIMATE2013=38280824, POPESTIMATE2014=38625139, POPESTIMATE2015=38953142, POPESTIMATE2016=39209127, POPESTIMATE2017=39399349, POPESTIMATE2018=39557045, STATE='06', STUSAB='CA', STATE_NAME='California'),
 Pandas(Index=43, PRIMGEO_FLAG=10, POPESTIMATE2012=26089620, POPESTIMATE2013=26489464, POPESTIMATE2014=26977142, POPESTIMATE2015=27486814, POPESTIMATE2016=27937492, POPESTIMATE2017=28322717, POPESTIMATE2018=28701845, STATE='48', STUSAB='TX', STATE_NAME='Texas'),
 Pandas(Index=32, PRIMGEO_FLAG=0, POPESTIMATE2012=19574549, POPESTIMATE2013=19628043, POPESTIMATE2014=19656330, POPESTIMATE2015=19661411, POPESTIMATE2016=19641589, POPESTIMATE2017=19590719, POPESTIMATE2018=19542209, STATE='36', STUSAB='NY', STATE_NAME='New York'),
 Pandas(Index=9, PRIMGEO_FLAG=0, POPESTIMATE2012=19326230, POPESTIMATE2013=19563166, POPESTIMATE2014=19860330, POPESTIMATE2015=20224249, POPESTIMATE2016=20629982, POPESTIMATE2017=20976812, POPESTIMATE2018=21299325, STATE='12', STUSAB='FL', STATE_NAME='Florida'),
 Pandas(Index=13, PRIMGEO_FLAG=0, POPESTIMATE2012=12884119, POPESTIMATE2013=12898269, POPESTIMATE2014=12888962, POPESTIMATE2015=12864342, POPESTIMATE2016=12826895, POPESTIMATE2017=12786196, POPESTIMATE2018=12741080, STATE='17', STUSAB='IL', STATE_NAME='Illinois')]